name: conselhos_estudo
description: Um app Flutter que gera conselhos de estudo com base em IA e voz.

publish_to: 'none' # Remova isso se for publicar

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  speech_to_text: ^7.0.0
  google_generative_ai: ^0.4.6
  flutter_dotenv: ^5.0.2

  # Flutter Material Design
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
